### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by Youssef-Najjarine** [youssefnajjarine/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Add a `div`  representing the green background.
- [x] Find an Image of a car.
- [x] Place the car into a div that's inside the green background div.
- [x] Style page so it looks like example template
- [x]  Ensure that the page looks nice on both mobile-sized and desktop-sized screens.
- [x]  Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Fix all errors.
