### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by Youssef-Najjarine** [youssefnajjarine/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [ ] Add a location to the data model to hold the car's x and y coordinates on the page.
- [ ] Use absolute positioning for your image.
- [ ] Use the style property of element objects to change your car's top and left box offset styles.
- [ ] Move your car every 16 milliseconds for a smooth movement.
